-- HH_DEV
USE WAREHOUSE DEV_WH;
USE DATABASE HH_DEV;
USE SCHEMA BRONZE_DB;

-- IMPORT DATA INTO DIM_CUSTTABLE
LIST '@HH_DEV.BRONZE_DB.INTERNAL_STAGE/Use case 4/CUSTTABLE.csv';

COPY INTO GOLD_DB.DIM_CUSTTABLE
    FROM '@HH_DEV.BRONZE_DB.INTERNAL_STAGE/Use case 4/CUSTTABLE.csv'
    FILE_FORMAT = (FORMAT_NAME = BRONZE_DB.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM GOLD_DB.DIM_CUSTTABLE;

SELECT * FROM GOLD_DB.DIM_CUSTTABLE;


-- IMPORT DATA INTO DIM_ACMRESIDENTREVIEW
LIST '@HH_DEV.BRONZE_DB.INTERNAL_STAGE/Use case 9/ECL_ACMRESIDENTREVIEW.csv';

COPY INTO GOLD_DB.DIM_ECL_ACMRESIDENTREVIEW
    FROM '@HH_DEV.BRONZE_DB.INTERNAL_STAGE/Use case 9/ECL_ACMRESIDENTREVIEW.csv'
    FILE_FORMAT = (FORMAT_NAME = BRONZE_DB.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

SELECT COUNT(*) FROM GOLD_DB.DIM_ECL_ACMRESIDENTREVIEW;