-- HH_DEV
USE WAREHOUSE DEV_WH;
USE DATABASE HH_DEV;
USE SCHEMA BRONZE_DB;

-- HH_TEST
-- USE WAREHOUSE TEST_WH;
USE DATABASE HH_TEST;
-- USE SCHEMA BRONZE_DB;

SHOW WAREHOUSES;

-- ECASE_ASSAULT_TYPES_RAW
CREATE OR REPLACE TABLE BRONZE_DB.ECASE_ASSAULT_TYPES_RAW (
    ID INTEGER,
    ShortDesc VARCHAR(20),
    LongDesc VARCHAR(100),
    HaslinkedSubtype BOOLEAN,
    LinkedSubtype INTEGER,
    IsArchived BOOLEAN,
    ChangeUser VARCHAR(50),
    ChangeDateTime TIMESTAMP,
    ModifiedDate TIMESTAMP,
    ModifiedUser VARCHAR(50)
);

-- ECASE_WOUND_TYPES_RAW
CREATE OR REPLACE TABLE BRONZE_DB.ECASE_WOUND_TYPES_RAW (
    Active INTEGER,
    WBT BOOLEAN,
    IsNQIP BOOLEAN,
    NQIPReports INTEGER,
    SortOrder INTEGER,
    ChangeUser VARCHAR(50),
    ChangeDateTime TIMESTAMP,
    ModifiedDate TIMESTAMP,
    ModifiedUser VARCHAR(50),
    Other VARCHAR(20)
);

-- ECASE_INCIDENT_TYPES_RAW
CREATE OR REPLACE TABLE BRONZE_DB.ECASE_INCIDENT_TYPES_RAW (
    ID INTEGER,
    ShortDesc VARCHAR(20),
    LongDesc VARCHAR(100),
    IsActivateFallsOnly BOOLEAN,
    HaslinkedSubtype BOOLEAN,
    LinkedSubtype INTEGER,
    IsArchived BOOLEAN,
    ChangeUser VARCHAR(50),
    ChangeDateTime TIMESTAMP,
    ModifiedDate TIMESTAMP,
    ModifiedUser VARCHAR(50)
);

-- ECASE_MEDINCIDENT_TYPES_RAW
CREATE OR REPLACE TABLE BRONZE_DB.ECASE_MEDINCIDENT_TYPES_RAW (
    ID INTEGER,
    ShortDesc VARCHAR(20),
    LongDesc VARCHAR(100),
    HaslinkedSubtype BOOLEAN,
    LinkedSubtype INTEGER,
    IsArchived BOOLEAN,
    ChangeUser VARCHAR(50),
    ChangeDateTime TIMESTAMP,
    ModifiedDate TIMESTAMP,
    ModifiedUser VARCHAR(50)
);

USE DATABASE HH_TEST;
DROP TABLE SILVER_DB.DIM_ASSAULT_TYPES;
DROP TABLE SILVER_DB.DIM_WOUND_TYPES;
DROP TABLE SILVER_DB.DIM_INCIDENT_TYPES;
DROP TABLE SILVER_DB.DIM_MEDINCIDENT_TYPES;


USE SCHEMA SILVER_DB;

-- DIM_ASSAULT_TYPES
CREATE OR REPLACE DYNAMIC TABLE SILVER_DB.ECASE_ASSAULT_TYPES_CONFORMED
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM BRONZE_DB.ECASE_ASSAULT_TYPES_RAW;

-- DIM_WOUND_TYPES
CREATE OR REPLACE DYNAMIC TABLE SILVER_DB.ECASE_WOUND_TYPES_CONFORMED
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM BRONZE_DB.ECASE_WOUND_TYPES_RAW;

-- DIM_INCIDENT_TYPES
CREATE OR REPLACE DYNAMIC TABLE SILVER_DB.ECASE_INCIDENT_TYPES_CONFORMED
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM BRONZE_DB.ECASE_INCIDENT_TYPES_RAW;

-- DIM_MEDINCIDENT_TYPES
CREATE OR REPLACE DYNAMIC TABLE SILVER_DB.ECASE_MEDINCIDENT_TYPES_CONFORMED
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM BRONZE_DB.ECASE_MEDINCIDENT_TYPES_RAW;

    
USE SCHEMA GOLD_DB;

-- DIM_ASSAULT_TYPES
CREATE OR REPLACE DYNAMIC TABLE GOLD_DB.DIM_ASSAULT_TYPES
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM SILVER_DB.ECASE_ASSAULT_TYPES_CONFORMED;

-- DIM_WOUND_TYPES
CREATE OR REPLACE DYNAMIC TABLE GOLD_DB.DIM_WOUND_TYPES
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM SILVER_DB.ECASE_WOUND_TYPES_CONFORMED;

-- DIM_INCIDENT_TYPES
CREATE OR REPLACE DYNAMIC TABLE GOLD_DB.DIM_INCIDENT_TYPES
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM SILVER_DB.ECASE_INCIDENT_TYPES_CONFORMED;

-- DIM_MEDINCIDENT_TYPES
CREATE OR REPLACE DYNAMIC TABLE GOLD_DB.DIM_MEDINCIDENT_TYPES
    TARGET_LAG = '15 minutes'
    WAREHOUSE = DEV_WH
AS
SELECT *
FROM SILVER_DB.ECASE_MEDINCIDENT_TYPES_CONFORMED;

-- FACT_INCIDENTS
CREATE OR REPLACE TABLE GOLD_DB.FACT_INCIDENTS (
    Status VARCHAR(7),
    BaseID VARCHAR(24),
    Program VARCHAR(11),
    IncidentDate TIMESTAMP,
    IncidentTimne TIMESTAMP,
    IncClassPrimary VARCHAR(209),
    InfType VARCHAR(100),
    Site VARCHAR(255),
    Incident_Location VARCHAR(50),
    IncidentCount BOOLEAN,
    RiskStrat BOOLEAN,
    SIRSIncType VARCHAR(10),
    SIRSVicPerp VARCHAR(100),
    Firstname VARCHAR(40),
    Surname VARCHAR(40),
    ResidentID INTEGER,
    Description VARCHAR,
    Detail VARCHAR,
    SIRSIncCat VARCHAR(100),
    SIRSDegreeHarm VARCHAR(500),
    ResidentType VARCHAR(50),
    ResidentStatus VARCHAR(11)
);

SHOW DATABASES;

DROP TABLE BRONZE_DB.DIM_ASSAULT_TYPES;
CREATE SCHEMA PUBLIC